name: setup-micromamba
description: 'Install micromamba package manager'
author: 'Pavel Zwerschke'
# TODO branding
# branding:
#   icon: "chevrons-right"
#   color: "green"
inputs:
  milliseconds:
    description: 'Number of milliseconds to wait'
    required: true
  condarc-file:
    description: >-
      Path to a condarc file to use
    default: '~/.condarc'
  environment-file:
    description: >-
      Path to the `environment.yml` or `.lock` file for the environment.
    default: 'environment.yml'
  environment-name:
    description: >-
      Name of the environment to create. Ovverrides the name in the environment file.
  extra-specs:
    description: >-
      Extra specs to install into the environment.
      For multiple packages, use multiline syntax:
      ```yml
      extra-specs: |
        - package1
        - package2
      ```
  create-args:
    description: >-
      Extra arguments to pass to `micromamba create`.
  create-env:
    description: >-
      Whether to create a micromamba environment. If `false`, the action will only install micromamba.
    default: 'true'
  log-level:
    description: >-
      Log level for micromamba.
      One of `'trace'`, `'debug'`, `'info'`, `'warning'`, `'error'`, `'critical'`, `'off'`.
    default: 'warning'
  micromamba-version:
    description: >-
      Version of micromamba to install.
    default: 'latest'
  micromamba-url:
    description: >-
      URL to download micromamba from.
  post-deinit:
    description: >-
      Whether to run `micromamba shell deinit` after the action or not.
    default: 'true'
  cache-downloads:
    description: >-
      Whether to cache downloads or not.
    default: 'true'
  cache-downloads-key:
    description: >-
      Cache key to use for caching.
  cache-env:
    description: >-
      Whether to cache the environment or not.
    default: 'true'
  cache-env-key:
    description: >-
      Cache key to use for caching.
runs:
  using: 'node16'
  main: 'dist/index.js'
