name: Pull Request Labeling

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]

jobs:
  pr-label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@0ac283b4e65c1fb28ce6079dea5546ceca98ccbe # v5.5.2
        with:
          labels: bug,enhancement,ci,documentation,dependencies,ignore-for-release
          mode: minimum
          count: 1
