name: Release if version changed

on:
  push:
    branches: main
permissions:
  contents: write

# To release a new version, update the version in package.json.
# This will create a draft release with the changelog and push a 'vx' tag that points to the new release as well as 'vx.y.z'.
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Quantco/ui-actions/version-metadata@5bfb8cebf0801e07c6a1c208a35b41637a3ff7fa # v1.0.20
        id: version-metadata
        with:
          file: ./package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: .github/scripts/release.sh
        if: steps.version-metadata.outputs.changed == 'true'
        env:
          TAG_NAME: v${{ steps.version-metadata.outputs.newVersion }}
      - name: Create release
        if: steps.version-metadata.outputs.changed == 'true'
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228
        with:
          generate_release_notes: true
          tag_name: v${{ steps.version-metadata.outputs.newVersion }}
          draft: true
